name: workflow.yml
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Execute Unit Tests for /analyzers
      run: python3 ci.py